### PR TITLE
Patch libEffekseerNativeForJava.dylib to work with Intel Macs

### PR DESCRIPTION
**Pull request by 4193883-eng**
Recompiled libEffekseerNativeForJava.dylib for x86_64.

### CODE REVIEW

**Comment by ChloePrime** [comment]
Will this work on ARM Macs too?

**Comment by nvb-uy** [comment]
What steps did you do to compile this @4193883-eng ?

**Comment by Leopapeo** [comment]
This library works on Intel Macs, but it is x86_64 only, so it does not work on Apple Silicon.

**Comment by 4193883-eng** [comment]
> This library works on Intel Macs, but it is x86_64 only, so it does not work on Apple Silicon.

it does. rosseta exists)

**Comment by 4193883-eng** [comment]
> What steps did you do to compile this @4193883-eng ?

recompiled and replaced the dylib

**Comment by 4193883-eng** [comment]
> Will this work on ARM Macs too?

it does. although it comes with a performance hit, it is negligible. if someone wants they can implement a switch case that loads an appropriate binary depending on the architecture. i won't as i am not experienced in java

**Comment by 4193883-eng** [comment]
although i could make a universal binary...
i'll think about that

**Comment by ChloePrime** [comment]
Please give me the universal binary, and use `Release` compile options (no debug symbols)

**Comment by Frontear** [comment]
Universal binary would definitely be preferred. Rosetta's performance hit especially in large modded contexts is going to be a real pain for users.

**Comment by ChloePrime** [comment]
LGTM. Merged as I don't have any mac too :)

**Pull request merged**
