### PR TITLE
Improvements aimed at making this mod a better dependency

### PR DESCRIPTION
**Pull request by ZigyTheBird**
Removed Architectury API dependency. (Added my own multiloader utility mod instead but it's included in the mod so no seperate download)
Made the lighting example only activate in a debug mode. (Mainly the dev environment)

I feel like these changes make the mod a lot better for use as a dependency in other mods but for whatever reason if you aren't gonna merge this pull request then I would like to ask for permission in order to have my version of the mod on my maven repository 🙏
Cool mod 👍

### CODE REVIEW

**Comment by ChloePrime** [comment]
Why not jarjar Architectury API?

**Comment by ZigyTheBird** [comment]
I personally don't like the idea of jarjaring other people's mods since it feels like I am stealing CF points from them
Other than that IDK :p

**Comment by ZigyTheBird** [comment]
You should really make the lighting example a dev environment thing only though

**Comment by ChloePrime** [comment]
Implemented similar functionality with my version in 1.2.1

**Comment by ChloePrime** [comment]
These dependencies are licences in LGPL and MPL-2.0, so Jarjar is ok :)

**Pull request closed without merging**
