### PR TITLE
Fix libEffekseerNativeForJava.so

### LINKED ISSUE #22: Crashes on latest Nvidia drivers on Linux
This issue seems to also effect the Eldritch End mod. When launched on Linux (Arch on Wayland) and Nvidia (Nvidia Open DKMs) you get the ``libEffekseerNativeForJava.so: undefined symbol: glGenSamplers`` error. Just putting this out there so you are aware. Also this seems to only happen to the 3.0 version. Previous versions do not seem to have this issue.

### LINKED ISSUE #34: Should this static link its required libraries?
I was informed by @ripjackie that this mod uses (or effekseer uses) `libglfw.so` and `libGLU.so`, but does not actually provide them, requiring both to be installed system-wide to have an effect.

Would it be possible to use the mc `libglfw.so` and statically link `libGLU.so`, or at least provide the shared object within the mod so it can load it in by itself, without requiring users to modify system state? It'd be hard to enforce for people, which is why I think this could be considered an ease-of-use problem.

### LINKED ISSUE #35: Hardcoded dependency on glibc causes a crash
Relevant log entries (this is from a LPS modpack called Prominence, I can share a similar crash report with just AAAParticles if necessary)

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'aaa_particles'!
    at app//net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
    at app//net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
    at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
    at app//net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
    at MC//net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
    at net.minecraft.client.main.Main.main(Main.java:211)
    at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
    at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
    at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError
    at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:55)
    at mod.chloeprime.aaaparticles.client.AAAParticlesClient.init(AAAParticlesClient.java:25)
    at mod.chloeprime.aaaparticles.fabric.AAAParticlesFabricClient.onInitializeClient(AAAParticlesFabricClient.java:15)
    at app//net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
    ... 9 more
Caused by: java.lang.UnsatisfiedLinkError: /home/ewerd/.local/share/PrismLauncher/instances/Prominence II RPG- Hasturian Era/minecraft/libEffekseerNativeForJava.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/ewerd/.local/share/PrismLauncher/instances/Prominence II RPG- Hasturian Era/minecraft/libEffekseerNativeForJava.so)
    at java.base@17.0.12/jdk.internal.loader.NativeLibraries.load(Native Method)
    at java.base@17.0.12/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
    at java.base@17.0.12/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
    at java.base@17.0.12/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
    at java.base@17.0.12/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
    at java.base@17.0.12/java.lang.Runtime.load0(Runtime.java:755)
    at java.base@17.0.12/java.lang.System.load(System.java:1957)
    at mod.chloeprime.aaaparticles.client.AAAParticlesClient.installNativeLibrary(AAAParticlesClient.java:53)
    ... 12 more
```

### LINKED ISSUE #37: Crash on startup
logs: https://mclo.gs/CWziiHs

OS: linux mint 21.3
Forge: 47.3.10
MC: 1.20.1
AAAParticles: 1.4.3

This mod causes a crash whenever it's loaded.

### PR DESCRIPTION
**Pull request by Frontear**
Closes #35
Closes #37
Closes #22
Closes #34
Closes #36

This fixes both the NVIDIA issues as well as the random libGLU link from the current one. Furthermore it also fixes the GLIBC issues simply by compiling off of a significantly older version (2.34). It should be a safe in-place drop (I have had 3 confirmations from affected users that this fix works).

For some details about how I built this library, or to replicate my results, please see https://github.com/Frontear/effekseer-libs.

### CODE REVIEW

**Review by nvb-uy — APPROVED** [review]
Would appreciate a ping when the fix is uploaded so I can update Prominence

**Comment by ripjackie** [comment]
@Frontear, I see you're building this against the original `effekseer/EffekseeForMultiLanguages`. That one is built against the `OPENGL_LIBRARIES` target, which will pull in libGLU if built on a system with it. That was the issue with my original build.

**Comment by ChloePrime** [comment]
LTGM

**Comment by Frontear** [comment]
> @Frontear, I see you're building this against the original `effekseer/EffekseeForMultiLanguages`. That one is built against the `OPENGL_LIBRARIES` target, which will pull in libGLU if built on a system with it. That was the issue with my original build.

Correct, which is why I ended up opting for a tight build sandbox using Nix. It's not necessarily the best solution but it consistently creates a valid binary and honestly that's the best case scenario for this.

**Comment by damianethorn** [comment]
A bit late but it worked for me on Mint 21.3 / Ubuntu 22.04.

**Pull request merged**
